### PR TITLE
sparky message

### PR DESCRIPTION
**Pull request by cengique**
adding in memoriam message to readme and checking Travis CI integration

### CODE REVIEW

**Comment by AsciiWolf** [comment]
What happened? :O

**Comment by cengique** [comment]
> What happened? :O

 @AsciiWolf Sorry we lost @dGr8LookinSparky to cancer. :cry: 

https://forum.grangerhub.org/t/in-memoriam-of-sparky/5359

I'm trying to get some maintenance releases out. Are you the one maintaining the flatpak?

**Comment by AsciiWolf** [comment]
I am so sorry to hear that. :-(( I have lost a loved one to cancer a year ago and I still can't get over it.

Yeah, I am the Flatpak maintainer (Sparky was the second one). I can ask for the push rights to its repository to be also added to you if you want. Regarding the releases, I have tried [updating the Flatpak to 0.15](https://github.com/flathub/com.grangerhub.Tremulous/pull/18), but it crashes for some reason.

I have also recently made a [Tremulous Snap](https://snapcraft.io/tremulous) for Ubuntu users, based on the official binary archive (unlike the Flatpak where I build game engine from source), and also tried updating Tremulous there - 0.15 works, but has some rendering/other issues (I have at least pushed it into beta channel) and 0.16 crashes.

**Comment by cengique** [comment]
@AsciiWolf sorry for your loss!

Thanks for the offer to add me. I don't have experience with Flatpak, but I'd be happy to learn/try. You can add me as second. I have the same account name on SnapCraft.

You're right, 0.16 crashes. I am removing the release temporarily. For 0.15, it is compiling and should be running fine. I did see a graphical glitch on the menu screen. Let me know if I can help debug either version.

I will add links to both of your versions into the README.

**Comment by cengique** [comment]
@wtfbbqhax do you mind reviewing this PR? Travis works now.

**Comment by AsciiWolf** [comment]
@cengique You can try the 0.15 Flatpak test build from here: https://github.com/flathub/com.grangerhub.Tremulous/pull/18#issuecomment-1557146558

The 0.15 [Snap](https://snapcraft.io/tremulous) seems to work fine, except for the graphical glitches.

**Pull request merged**
